### ISSUE TITLE
Mount folder in container to host?

### ISSUE THREAD

**Issue by psiie** [ryankurte/docker-rpi-emu#12]
Is it possible to mount a folder inside the container to the host? I have tried countless times mounting folders using the -v flag in docker, but I have a strange suspicion that due to the emulation it is not possible. 

Thoughts? Ideas?

**Comment by ryankurte** [comment]
So this whole docker emulation thing is kindof turtles all the way down, if you have a linux (or *maybe* osx) machine & are willing to play with the scripts you should be able to get it running natively which is way more sensible IMO.

If you want a mounted folder to be available within the image you're probably going to need to `-v` it into the docker machine, then, after mounting the disk image but before the [chroot](https://github.com/ryankurte/docker-rpi-emu/blob/master/scripts/run.sh#L35) symlink from a directory in the mounted image back to the share in the docker machine.

I /think/ it should be possible / totally work, but, will be interested to hear back how it goes ^_^

**Comment by maxmcd** [comment]
Symlinking didn't work for me. Was able to -v and then `mount --bind` before running `chroot`

docker-compose.yml
```yml
#...
emulated:
  build: 
    context: .
    dockerfile: pi.Dockerfile
  privileged: true
  volumes:
    - ./:/usr/rpi/images
    - ./:/opt/app
  command: ./run-rpi-emu.sh images/voltlet.1.1.8.mini.img /bin/bash
```

Important bits of my https://github.com/ryankurte/docker-rpi-emu/blob/625d8813ea/scripts/run.sh replacement.
```bash
#...
# Mount ISO
./mount.sh $1 $MOUNT_DIR

mkdir "$MOUNT_DIR/opt/app"
mount --bind /opt/app /media/rpi/opt/app
#...
```
